export enum PurchaseOrderType {
    TIEP = 1,
    NON_TIEP = 2,
    MP = 3,
}

export enum CustomerType {
    CUSTOMER = "customer",
    SUPPLIER = "supplier",
    BOTH = "both",
}

export enum QuotationStatus {
    PENDING = "PENDING",
    CREATED = "CREATED",
    APPROVED = "APPROVED",
    COMPLETED = "COMPLETED",
    REJECTED = "REJECTED",
}

export enum PurchaseOrderStatus {
    PENDING = "PENDING",
    CREATED = "CREATED",
    APPROVED = "APPROVED",
    COMPLETED = "COMPLETED",

}

export enum JobTicketStatus {
    CREATED = "CREATED",
    APPROVED = "APPROVED",
    MATERIALS_REQUESTED = "MATERIALS_REQUESTED",
    MATERIALS_ALLOCATED = "MATERIALS_ALLOCATED",
    IN_PRINTING = "IN_PRINTING",
    PRINTING_COMPLETED = "PRINTING_COMPLETED",
    PARTIALLY_DISPATCHED = "PARTIALLY_DISPATCHED",
    DISPATCHED = "DISPATCHED",
    COMPLETED = "COMPLETED",
}

export enum CustomerStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
}

export enum TaxTypes {
    NON = 'NON',
    SVAT = "SVAT",
    VAT = "VAT",
}

export enum QuotationType {
    NORMAL = 1,
    OPTIONAL = 2,
}

export enum QuotationTaxType {
    VAT = 0,
    SVAT = 1,
    NONE = 2,
}


export enum VatType {
    SVAT = "SVAT",
    VAT = "VAT",
}


export enum ITEM_CATEGORY {
    PAPER = "PAPER",
    BOARD = "BOARD",
    CHEMICALS = "CHEMICALS",
    GLUE = "GLUE",
    INK = "INK",
    LAMINATING_FILM = "LAMINATING FILM",
    MISCELLANEOUS = "MISCELLANEOUS",
    PRE_PRESS = "PRE-PRESS",
    SPIRAL = "SPIRAL"
}

export enum ITEM_SUB_CATEGORY {
    BLANKS = "BLANKS",
    ART_BOARD = "ART BOARD",
    ART_PAPER = "ART PAPER",
    BLANK_PAPER = "BLANK PAPER",
    BOX_BOARD = "BOX BOARD",
    CLEANING = "CLEANING",
    COUTED_PAPER_BOARD = "COUTED PAPER BOARD",
    GLUE = "GLUE",
    INK = "INK",
    IVORY_BOARD = "IVORY BOARD",
    LAMINATING_FILM = "LAMINATING FILM",
    LINEN_PAPER = "LINEN PAPER",
    NEWS_PRINT_PAPER = "NEWS PRINT PAPER",
    OP = "OP",
    OTHER = "OTHER",
    SPIRAL = "SPIRAL",
}

export enum UNIT_OF_MEASSURE {
    NOS = "NOS",
    REEL = "REEL",
    SHEET = "SHEET",
    LTR = "LTR",
    KG = "KG",
}

export enum PLATES_STATUS {
    PLATES_REQUESTED = "PLATES REQUESTED",
    PLATES_RECEIVED = "PLATES RECEIVED",
}

export enum INK_STATUS {
    AVAILABLE = "AVAILABLE",
    NOT_AVAILABLE = "NOT AVAILABLE",
}


export enum PRODUCT_TYPES {
    MASTER_CARTON = "MASTER CARTON",
    INNER_CARTON = "INNER CARTON",
    STICKER = "STICKER",
    LEAFLET = "LEAFLET",
    BOOK_COVER = "BOOK COVER"
}
export enum PAPER_TYPES {
    ART_PAPER_120_GSM_MATTE = "ART PAPER 120 GSM MATTE",
    ART_PAPER_150_GSM_MATTE = "ART PAPER 150 GSM MATTE",
    LINEN_PAPER_100_GSM_GLOSS = "LINEN PAPER 100 GSM GLOSS",
    LINEN_PAPER_150_GSM_GLOSS = "LINEN PAPER 150 GSM GLOSS",
    BLANK_PAPER_55_GSM = "BLANK PAPER 55 GSM",
    BLANK_PAPER_70_GSM = "BLANK PAPER 70 GSM",
    BLANK_PAPER_80_GSM = "BLANK PAPER 80 GSM",
    BLANK_PAPER_100_GSM = "BLANK PAPER 100 GSM",
    BLANK_PAPER_120_GSM = "BLANK PAPER 120 GSM",
    BOX_BOARD_250_GSM_WB = "BOX BOARD 250 GSM W/B",
    BOX_BOARD_300_GSM_WB = "BOX BOARD 300 GSM W/B",
    BOX_BOARD_350_GSM_WB = "BOX BOARD 350 GSM W/B",
    IVORY_BOARD_230_GSM = "IVORY BOARD 230 GSM",
    IVORY_BOARD_250_GSM = "IVORY BOARD 250 GSM",
    IVORY_BOARD_300_GSM = "IVORY BOARD 300 GSM",
    IVORY_BOARD_350_GSM = "IVORY BOARD 350 GSM",
    ART_BOARD_230_GSM = "ART BOARD 230 GSM",
    ART_BOARD_260_GSM = "ART BOARD 260 GSM",
    BOX_BOARD_250_GSM_GB = "BOX BOARD 250 GSM G/B",
    BOX_BOARD_250_GSM_GB_G = "BOX BOARD 250 GSM G/B - G",
    BOX_BOARD_250_GSM_GB_R = "BOX BOARD 250 GSM G/B - R",
    BOX_BOARD_250_GSM_GB_KSPA = "BOX BOARD 250 GSM G/B - KSPA",
    BOX_BOARD_300_GSM_GB = "BOX BOARD 300 GSM G/B",
    BOX_BOARD_320_GSM_GB = "BOX BOARD 320 GSM G/B",
    BOX_BOARD_350_GSM_GB = "BOX BOARD 350 GSM G/B",
    BOX_BOARD_450_GSM_GB = "BOX BOARD 450 GSM G/B",
    BOX_BOARD_450_GSM_GB_R = "BOX BOARD 450 GSM G/B - R",
    NEWS_PRINT_PAPER_45_GSM = "NEWS PRINT PAPER 45 GSM",
    NEWS_PRINT_PAPER_48_8_GSM = "NEWS PRINT PAPER 48.8 GSM",
    GRAY_BOARD_900_GSM = "GRAY BOARD 900 GSM",
    CHIP_BOARD = "CHIP BOARD",
    PLAYING_BOARD_270_GSM = "PLAYING BOARD 270 GSM",
    NCR_55_YELLOW_BOT = "NCR 55 - YELLOW BOT",
    NCR_80_WHITE_TOP = "NCR 80 - WHITE TOP",
    STICKER_PAPER = "STICKER PAPER",
    STICKER_PAPER_OGI = "STICKER PAPER OGI",
    STICKER_PAPER_GLOSS_VERITAC = "STICKER PAPER GLOSS - VERITAC",
    TEST_INNER_PAPER_150_GSM = "TEST INNER PAPER 150 GSM",
}


export enum COATING_TYPES {
    UV_VARNISHED = "UV VARNISHED",
    OP_VARNISHED = "OP VARNISHED",
    COLD_LAMINATED = "COLD LAMINATED",
    MATT_LAMINATED = "MATT LAMINATED",
    SPOT_UV_VARNISHED = "SPOT UV VARNISHED",
    FOILED = "FOILED",
    EMBOSING = "EMBOSING",
    SAND_UV_VARNISHED = "SAND UV VARNISHED",

}

export enum REPORT_TYPES {
    JOB_PRODUCTION = "JOB PRODUCTION",
    QUOTATION_SUMMARY = "QUOTATION SUMMARY",
    QUOTE_TO_PO_CONVERSION = "QUOTE TO PO CONVERSION",
    INVENTORY_HEALTH = "INVENTORY HEALTH",
    DISPATCH_INSIGHTS = "DISPATCH INSIGHTS",
}

export enum USER_ROLES {
    USER = "USER",
    ADMIN = "ADMIN",
}